use: 'api' # import or api

model_import:
  name: 'llama-2'
  # pretrained: true
  temperature: 0.2
  max_new_tokens: 4000
  do_sample: true
  top_p: 0.9
  tokenizer:
    name: 'llama-2'
  quantization: false
  #training:
  #  output_dir: ''
  #  epochs: ''
  #  save_steps: ''


model_api:
  name: 'gpt'
  label: 'gpt3-5'
  version: '3.5-turbo' # Used with GPT only up to now
  api_version: '2024-02-15-preview' # Used with GPT only up to now
  max_tokens:
  n_responses: 1
  temperature: 0.1
  stop:
  top_p: 0.9
  top_k: 5 # Only a gemini parameter?

exercise:
  name: 'exercise-1'
  version: 'sql'
  prompt_version: 'v4'

debug_prints: false
