use: 'import'

model_import:
  name: 'falcon'
  key: '' # huggingface key
  # pretrained: true
  temperature: 0.7 # not using at the moment TODO check if it's supported
  tokenizer:
    name: 'falcon'
  quantization: False
  #training:
  #  output_dir: ''
  #  epochs: ''
  #  save_steps: ''


model_api:
  name: 'gpt-3.5-turbo'
  key: ''
  max_tokens: ''
  role: 'user'
  n_responses: 1
  temperature: 0.7
  stop:

exercise:
  name: ''
