use: 'api' # import or api

model_import:
  name: 'llama-2'
  key: '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' # huggingface key
  # pretrained: true
  temperature: 0.2
  max_new_tokens: 4000
  do_sample: true
  top_p: 0.9
  tokenizer:
    name: 'llama-2'
  quantization: false
  #training:
  #  output_dir: ''
  #  epochs: ''
  #  save_steps: ''


model_api:
  name: 'gemini'
  key: 'AIzaSyDwGHqgxy9PJXBvpwklfp-eI_VdjBRj9B4'
  max_tokens:
  n_responses: 1
  temperature: 0.7
  stop:
  top_p: 0.6
  top_k: 5 # Only a gemini parameter?

exercise:
  name: 'exercise-2.3-sql'
  prompt_version: 'v1'

debug_prints: true
