use: 'import'

model_import:
  name: 'falcon'
  key: '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' # huggingface key
  # pretrained: true
  temperature: 0.2
  max_new_tokens: 4000
  do_sample: true
  top_p: 0.9
  tokenizer:
    name: 'falcon'
  quantization: false
  #training:
  #  output_dir: ''
  #  epochs: ''
  #  save_steps: ''


model_api:
  name: 'gpt-3.5-turbo'
  key: '' # legacy only
  max_tokens: ''
  n_responses: 1
  temperature: 0.7
  stop:

exercise:
  name: 'exercise-2.3-sql'
  prompt_version: 'v1'

debug_prints: true
