exercise:
  full_name: # Can specify exercise full name, without .yml extensions
  name: 'exercise-2.3'
  v: 'sql'
  prompt_v: 'v1'
  latest: true # Optional in case of full_name
  timestamp: # Optional in case of full_name

model:
  name: 'gpt'
  v: '' # Optional

visualization:
  node_color: true
  edge_color: true
  k: 2.0 # Regulates distance between nodes
  arrowsize: 20 # Regulates edges' arrow pointer dimension
  image:
    generate: true # Generates the image
    format: 'png'
  show_graph: true # Regulates graph plot
