exercise:
  full_name: # Can specify exercise full name, without .yml extensions
  name: 'exercise-2.3'
  v: 'sql'
  prompt_v: 'v1'

model:
  name: 'gpt'
  v: '' # Optional

output:
  latest: true
  timestamp: